
services:
  web:
      build: .
      ports:
        - "5000:5000"
      volumes:
        - .:/app
      environment:
        - FLASK_ENV=development
      depends_on:
        - db
  db:
    image: postgres:latest
    container_name: voice_project_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: KGPDV@108  # Set your password here
      POSTGRES_DB: voice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
